## week2 Logistic regression(2-class)

* 참고 사이트
cross entropy gradient, https://kakalabblog.wordpress.com/2017/04/04/cross-entropy-%EC%A0%95%EB%A6%AC/

https://madalinabuzau.github.io/2016/11/29/gradient-descent-on-a-softmax-cross-entropy-cost-function.html


In [1]:
# 실습에 필요한 라이브러리를 불러옵니다.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# 데이터를 불러옵니다.
data = pd.read_csv('data/data.txt', header=None)
data.head()

0          1  2
0  34.623660  78.024693  0
1  30.286711  43.894998  0
2  35.847409  72.902198  0
3  60.182599  86.308552  1
4  79.032736  75.344376  1

In [3]:
data = np.array(data)
X = data[:, [0,1]]
y = data[:, 2]

print(X.shape)
print(y.shape)

(100, 2)
(100,)


In [9]:
#배열 
x_1 = np.zeros((X.shape[0], 1))
x_2 = np.concatenate((x_1, X), axis=1)
x_2.shape

In [28]:
#np.sum axis 설정 
print(x_1.shape)
print(y.shape)
print(np.sum(x_2.T* y, axis=1))
print(np.sum(x_2.T* y, axis=0))

(100, 1)
(100,)
[   0.         4483.1353618  4437.38412496]
[  0.           0.           0.         146.49115148 154.37711249
   0.         157.61809042 121.57875911 163.51935642 127.96621327
   0.           0.         158.78901668 167.08328072   0.
 143.17840229 121.81061379   0.         163.58864745 124.55474738
   0.         155.47614168   0.           0.         146.89645145
 132.22547162 125.01180968   0.           0.           0.
 134.18717676 142.45650337   0.         121.47826489   0.
   0.           0.         145.08504946   0.           0.
 140.21043988   0.         160.01228937   0.           0.
   0.         147.65123493 184.49942161 158.84188792 180.26126704
 154.10793729 160.27155793 133.93731592   0.           0.
   0.         166.50720668   0.         144.07326259 150.2500243
 161.15554814   0.           0.           0.           0.
   0.         137.99273647   0.         172.39563483 127.7381126
   0.         142.07100844 168.57408719 133.55288384 134.69940453
 172.197

In [24]:
# 모델을 학습합니다.
class LogisticRegression:
    def __init__(self, lr = 0.01, num_iter = 100, fit_intercept = True):
        self.lr = lr
        self.num_iter = num_iter
        self.fit_intercept = fit_intercept
        
    def add_intercept(self, X): #beta_0에 대한 추정을 하기 위해 1인 배열 추가, y = X^T * B(X = [1, X], B = [beta_0, beta_1]
        intercept = np.ones((X.shape[0], 1)) #1로 초기화하는 2차원 배열 생성
        return np.concatenate((intercept, X), axis=1)
    #np.concatenate : 여러개의 배열을 하나로 합치는 함수, axis = 0(y축), axis=1(x축)
    
    def sigmoid(self, z): #sigmoid함수 선언
            self.z = z
            sigmoid = 1 / (1+ np.exp(-z))
            return sigmoid
    
    def loss(self, h, y): #cross-entropy 방식의 loss 선언
            loss = np.sum(-(y*np.log(h) + (1-y)*np.log(1-h))) / X.shape[0]
            return loss
    
    def fit(self, X, y): #모델 학습 과정
        if self.fit_intercept:
            X = self.add_intercept(X)
            print(X.shape)
            
        self.theta = np.zeros(X.shape[1])
            
        for i in range(self.num_iter):
            z = np.dot(X, self.theta) # y_pred = X*W
            h = self.sigmoid(z)
            gradient = np.sum(X.T * (h-y), axis=1) / X.shape[0]
            self.theta = self.theta - self.lr * gradient
            print(self.theta)
            
            z = np.dot(X, self.theta)
            h = self.sigmoid(z)
            loss = self.loss(h, y)
            
        return z, h, loss
    
    def predict_prob(self, X):
        if self.fit_intercept:
            X = self.add_intercept(X)
    
        return self.sigmoid(np.dot(X, self.theta))
            
    def predict(self, X):
        return self.predict_prob(X).round()

In [25]:
model = LogisticRegression()
model.fit(X, y)

(100, 3)
[0.001      0.12009217 0.11262842]
[-0.00299992 -0.08803412 -0.10584942]
[0.00299971 0.36026435 0.33787159]
[-0.00100029  0.15213514  0.11939003]
[-0.00500027 -0.05599341 -0.09909066]
[0.00099766 0.39222165 0.34455138]
[-0.00300234  0.18409245  0.12606982]
[-0.00700234 -0.0240366  -0.09241153]
[-0.00101746  0.42339398  0.35062696]
[-0.00501746  0.21526477  0.13214539]
[-0.00901746  0.00713561 -0.08633612]
[-0.00315988  0.4455214   0.35082561]
[-0.00715988  0.23739219  0.13234404]
[-0.01115988  0.02926301 -0.0861375 ]
[-0.00576927  0.43156684  0.32908994]
[-0.00976927  0.22343763  0.11060837]
[-0.01376926  0.01530852 -0.10787307]
[-0.00786653  0.45653293  0.331599  ]
[-0.01186653  0.24840372  0.11311743]
[-0.01586653  0.04027455 -0.10536409]
[-0.01043864  0.44390591  0.31268249]
[-0.01443864  0.23577671  0.09420093]
[-0.01843864  0.02764763 -0.12428046]
[-0.01255658  0.46693648  0.31443785]
[-0.01655658  0.25880728  0.09595628]
[-0.02055657  0.05067813 -0.1225252 ]
[-0.01513562

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in log
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: RuntimeWarning: invalid value encountered in multiply


(array([ 5.35690945,  6.64811353,  6.18679445, 13.35864178, 20.6421419 ,
        10.66318185, 12.84627256, 21.61275116, 18.66908248, 25.04948231,
        29.35700558, 22.90018274, 21.66105102, 15.55050874,  7.18540607,
        11.01637268, 19.09153341, 19.20109787, 16.37843207, 22.19304235,
        19.31690957, 25.02638478, 13.11683508,  7.95454734, 20.78177904,
        15.3910969 , 23.50564848, 28.37829841, 16.83608533,  7.82383217,
        14.85754798, 24.28487251, 12.49534274, 11.96370959,  7.81657443,
        14.23626518,  3.42927052, 15.15112504, 21.93602039,  5.43321016,
        23.83541314, 13.62238771, 26.66237202, 24.58510919, 13.53641316,
        16.82314952, 20.41345029, 26.07887393, 13.15334152, 23.81358394,
        21.04723802, 28.67086149, 27.13552181,  6.75026188, 12.95578976,
        11.90849224, 27.48238398,  3.23995173, 19.46570845, 17.93514628,
        18.56491713,  8.09143373, 15.83398564,  6.10954552,  9.70205288,
        19.18305137,  5.75703326, 12.37562909, 19.7

In [ ]:
# 결과를 출력합니다.
plt.scatter(X[y == 0][:, 0], X[y == 0][:, 1], color='b', label='0')
plt.scatter(X[y == 1][:, 0], X[y == 1][:, 1], color='r', label='1')
plt.legend()

x1_min, x1_max = X[:,0].min(), X[:,0].max(),
x2_min, x2_max = X[:,1].min(), X[:,1].max(),
xx1, xx2 = np.meshgrid(np.linspace(x1_min, x1_max), np.linspace(x2_min, x2_max))

grid = np.c_[xx1.ravel(), xx2.ravel()]
probs = model.predict_prob(grid).reshape(xx1.shape)
plt.contour(xx1, xx2, probs, [0.5], linewidths=1, colors='black');

plt.savefig("binary_classification.png") 
#eu.send_image("binary_classification.png")

In [ ]:
# 실습에 필요한 라이브러리를 불러옵니다. 원본 실습코드
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 데이터를 불러옵니다.
data = pd.read_csv('data/data.txt', header=None)
data = np.array(data)
X = data[:, [0,1]]
y = data[:, 2]


# Logistic 회귀 모델을 구현합니다.
class LogisticRegression:
    def __init__(self, lr=0.01, num_iter=300000, fit_intercept=True):
        self.lr = lr
        self.num_iter = num_iter
        self.fit_intercept = fit_intercept
    
    def add_intercept(self, X):
        intercept = np.ones((X.shape[0], 1))
        return np.concatenate((intercept, X), axis=1)
    
    # sigmoid 함수를 작성하세요.
    def sigmoid(self, z):
        return None
    
    # loss 함수를 작성하세요.
    def loss(self, h, y):
        return None
    
    # 모델을 학습하는 fit 함수를 작성하세요.
    def fit(self, X, y):
        if self.fit_intercept:
            X = self.add_intercept(X)
        
        self.theta = None
        
        for i in range(self.num_iter):
            z = None
            h = None
            gradient = None
            self.theta = None
            
            z = None
            h = None
            loss = None
        
        return z, h, loss
    
    def predict_prob(self, X):
        if self.fit_intercept:
            X = self.add_intercept(X)
    
        return self.sigmoid(np.dot(X, self.theta))
    
    # predict_prob 함수를 이용해 predict 함수를 완성하세요.
    def predict(self, X):
        return self.predict_prob(X).round()
        
    
# 모델을 학습합니다.
model = None
model.fit(X, y)


# 결과를 출력합니다.
plt.scatter(X[y == 0][:, 0], X[y == 0][:, 1], color='b', label='0')
plt.scatter(X[y == 1][:, 0], X[y == 1][:, 1], color='r', label='1')
plt.legend()

x1_min, x1_max = X[:,0].min(), X[:,0].max(),
x2_min, x2_max = X[:,1].min(), X[:,1].max(),
xx1, xx2 = np.meshgrid(np.linspace(x1_min, x1_max), np.linspace(x2_min, x2_max))

grid = np.c_[xx1.ravel(), xx2.ravel()]
probs = model.predict_prob(grid).reshape(xx1.shape)
plt.contour(xx1, xx2, probs, [0.5], linewidths=1, colors='black');

plt.savefig("binary_classification.png") 
eu.send_image("binary_classification.png")